### PR TITLE
Fix @mention notifications

### PR DESCRIPTION
**Pull request by maebeam**

### CODE REVIEW

**Review by 2000c5 — COMMENTED** [review]
Want to make sure the fix is not to only catch commas and other standard "terminators" other than space?

All the cases I have seen were followed by a space.

**Comment by maebeam** [comment]
I'm not sure I understand your comment. The terminators are relevant both before and after the @mention. Prior to this change a mention not followed or preceded by a space would fail.

**Comment by 2000c5** [comment]
> I'm not sure I understand your comment. The terminators are relevant both before and after the @mention. Prior to this change a mention not followed or preceded by a space would fail.

My apologies... Just wanted to make sure.

Thank you for your efforts!

**Review by lazynina — APPROVED** [review]
:rocket:

**Pull request merged**
